services:
  app:
    build:
      x-bake: false
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres
      - SPRING_DATASOURCE_USERNAME=postgres.zkviewvpmswfgpiwpoez
      - SPRING_DATASOURCE_PASSWORD=N2VNFeSJNAbiPi7E