spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tareas
    username: usuario
    password: contrase√±a
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update