spring:
  datasource:
    url: jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres
    username: postgres.zkviewvpmswfgpiwpoez
    password: N2VNFeSJNAbiPi7E
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update